name: Desplegar a AWS ECR y ECS

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código fuente
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y subir la imagen Docker
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: api-core
        IMAGE_TAG: ${{ github.sha }} 
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Descargar definición de tarea actual
      run: |
        aws ecs describe-task-definition \
          --task-definition api-payment-def-v1 \
          --query taskDefinition > task-definition.json

    - name: Insertar la nueva imagen en la Definición de Tarea
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Main 
        image: ${{ steps.build-image.outputs.image }}

    - name: Desplegar la nueva Definición de Tarea en Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: api-payment-def-v1-service-x0ksd7bq
        cluster: default
        wait-for-service-stability: true 
